name: ML Pipeline CI/CD

on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  pull_request:
    branches: [ "main" ]  # Trigger on PRs targeting main branch

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: |
            python -m venv venv
            echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
  
      - name: Debug Python paths
        run: |
            which python
            python --version
            ls -l venv/bin/python
            ls -l venv/bin/python3
  
      - name: Install dependencies
        run: |
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - name: prepare
        run: |
          export MLFLOW_TRACKING_URI=""
          python main.py --prepare

      - name: train data
        run: make train

      - name: eval data
        run: make evaluate

      - name: Code quality checks
        run: make check-code