name: ML Pipeline CI/CD

# Define triggers
on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  pull_request:
    branches: [ "main" ]  # Trigger on PRs targeting main branch

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Create virtual environment and install dependencies
        run: |
          echo "Creating virtual environment and installing dependencies..."
          python3.9 -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt
          echo "Dependencies installed."
       
      - name: prepare 
        run: make prepare

      - name: train data
        run: make train

      - name: eval data
        run: make evaluate

      - name: Code quality checks
        run: make check-code


 

